"""
triple_builder.py — Convert enriched entities + relationships
into an rdflib Graph with proper OWL class hierarchy,
object properties (with domain/range), and datatype properties.
Produces a Protege-ready OWL ontology.
"""

import re
from rdflib import (Graph, Namespace, URIRef, Literal,
                    RDF, RDFS, OWL, XSD)
from rdflib.namespace import DC, FOAF, SKOS

# ── Namespaces ────────────────────────────────────────────
BASE_URI = "http://iiitb.ac.in/ontology/autonomous#"
ONTO = Namespace(BASE_URI)
SCHEMA = Namespace("https://schema.org/")


def _safe_uri(id_str: str) -> URIRef:
    """Convert any string to a safe URI fragment."""
    # Handle already safe IDs or URLs
    if str(id_str).startswith("http"):
        return URIRef(id_str)
    
    safe = re.sub(r"[^a-zA-Z0-9_\-]", "_",
                  str(id_str).strip())
    safe = re.sub(r"_+", "_", safe).strip("_")
    return ONTO[safe or "unknown"]


def _xsd_range(type_str: str) -> URIRef:
    """Resolve xsd:type string to rdflib XSD URI."""
    if not type_str:
        return XSD.string
    t = type_str.replace("xsd:", "").strip()
    return XSD[t] if t else XSD.string


def build_graph(enriched_list: list) -> Graph:
    """
    Build a fully autonomous OWL graph by merging RDF/XML snippets
    generated by the LLM. No hardcoded mapping logic.
    """
    master_graph = Graph()

    # Bind common namespaces for readability
    master_graph.bind("onto",   ONTO)
    master_graph.bind("owl",    OWL)
    master_graph.bind("rdfs",   RDFS)
    master_graph.bind("xsd",    XSD)
    master_graph.bind("dc",     DC)
    master_graph.bind("schema", SCHEMA)

    print(f"\n  [triples] Merging {len(enriched_list)} enriched chunks...")

    success_count = 0
    fail_count = 0

    for i, item in enumerate(enriched_list):
        if isinstance(item, str):
            try:
                # Parse the snippet into a temporary graph
                temp_g = Graph()
                
                # Try Turtle first (more robust for LLMs)
                try:
                    temp_g.parse(data=item, format="turtle")
                except Exception as turtle_err:
                    # Fallback to XML
                    try:
                        temp_g.parse(data=item, format="xml")
                    except Exception as xml_err:
                        print(f"    [triples] ⚠ Chunk {i+1} parse failed:")
                        print(f"      - Turtle error: {str(turtle_err).strip()}")
                        print(f"      - XML error:    {str(xml_err).strip()}")
                        fail_count += 1
                        continue
                
                # Sanity check: iterate through triples and fix "pseudo-URIs" 
                # that are actually literals (LLM hallucination)
                for s, p, o in temp_g:
                    if isinstance(o, URIRef):
                        o_str = str(o)
                        # If URI contains spaces or doesn't look like a URI, convert to Literal
                        if " " in o_str or (len(o_str) > 150 and "://" not in o_str):
                            master_graph.add((s, p, Literal(o_str)))
                        else:
                            master_graph.add((s, p, o))
                    else:
                        master_graph.add((s, p, o))
                
                success_count += 1
            except Exception as e:
                print(f"    [triples] ⚠ Chunk {i+1} unexpected error: {e}")
                fail_count += 1
        elif isinstance(item, dict):
            print(f"    [triples] ⚠ Chunk {i+1} skipped (LLM error: {item.get('error', 'unknown')})")
            fail_count += 1

    # ── Ensure Ontology Header ──────────────────────────
    onto_uri = URIRef(BASE_URI)
    if (onto_uri, RDF.type, OWL.Ontology) not in master_graph:
        master_graph.add((onto_uri, RDF.type, OWL.Ontology))
        master_graph.add((onto_uri, DC.title, 
                          Literal("Autonomous Institutional Knowledge Graph", lang="en")))
        master_graph.add((onto_uri, DC.description,
                          Literal("Emergent OWL ontology generated by autonomous pipeline.", lang="en")))
        master_graph.add((onto_uri, OWL.versionInfo, Literal("3.0-emergent")))

    print(f"  [triples] ✓ Merging complete:")
    print(f"    Total triples : {len(master_graph)}")
    print(f"    Chunks merged : {success_count}")
    print(f"    Chunks failed : {fail_count}")

    return master_graph

