"""
triple_builder.py — Convert enriched entities + relationships
into an rdflib Graph with proper OWL class hierarchy,
object properties (with domain/range), and datatype properties.
Produces a Protege-ready OWL ontology.
"""

import re
from rdflib import (Graph, Namespace, URIRef, Literal,
                    RDF, RDFS, OWL, XSD)
from rdflib.namespace import DC, FOAF, SKOS

# ── Namespaces ────────────────────────────────────────────
BASE_URI = "http://iiitb.ac.in/ontology/autonomous#"
ONTO = Namespace(BASE_URI)
SCHEMA = Namespace("https://schema.org/")


def _safe_uri(id_str: str) -> URIRef:
    """Convert any string to a safe URI fragment."""
    # Handle already safe IDs or URLs
    if str(id_str).startswith("http"):
        return URIRef(id_str)
    
    safe = re.sub(r"[^a-zA-Z0-9_\-]", "_",
                  str(id_str).strip())
    safe = re.sub(r"_+", "_", safe).strip("_")
    return ONTO[safe or "unknown"]


def _xsd_range(type_str: str) -> URIRef:
    """Resolve xsd:type string to rdflib XSD URI."""
    if not type_str:
        return XSD.string
    t = type_str.replace("xsd:", "").strip()
    return XSD[t] if t else XSD.string


def build_graph(enriched_list: list) -> Graph:
    """
    Build a fully autonomous OWL graph from enriched chunks.
    No hardcoded schema used.
    """
    g = Graph()

    # Bind namespaces
    g.bind("onto",   ONTO)
    g.bind("owl",    OWL)
    g.bind("rdfs",   RDFS)
    g.bind("xsd",    XSD)
    g.bind("foaf",   FOAF)
    g.bind("schema", SCHEMA)
    g.bind("dc",     DC)
    g.bind("skos",   SKOS)

    # ── Ontology header ───────────────────────────────────
    onto_uri = URIRef(BASE_URI)
    g.add((onto_uri, RDF.type, OWL.Ontology))
    g.add((onto_uri, DC.title,
           Literal("Autonomous Institutional Knowledge Graph",
                    lang="en")))
    g.add((onto_uri, DC.description,
           Literal("Schema-less OWL ontology generated by "
                   "autonomous semantic discovery pipeline.",
                   lang="en")))
    g.add((onto_uri, OWL.versionInfo,
           Literal("2.0-schema-less")))

    # Keep track of declared classes/properties to avoid duplicates
    declared_classes = set()
    declared_props = set()

    total_entities = 0
    total_rels = 0
    skipped_rels = 0

    for chunk_idx, chunk_result in enumerate(enriched_list):
        if not isinstance(chunk_result, dict):
            continue

        entities  = chunk_result.get("entities", [])
        rels      = chunk_result.get("relationships", [])
        annots    = chunk_result.get("owl_annotations", {})

        # ── 1. Process Class Hierarchy ────────────────────
        hierarchy = annots.get("class_hierarchy", {})
        for cls_name, parent_name in hierarchy.items():
            cls_uri = ONTO[cls_name]
            parent_uri = ONTO[parent_name] if parent_name != "Thing" else OWL.Thing
            
            g.add((cls_uri, RDF.type, OWL.Class))
            g.add((cls_uri, RDFS.label, Literal(cls_name)))
            g.add((cls_uri, RDFS.subClassOf, parent_uri))
            declared_classes.add(cls_name)

        # ── 2. Add entities as OWL Named Individuals ──────
        for ent in entities:
            if not isinstance(ent, dict):
                continue
            eid_str  = ent.get("id", "")
            etype    = ent.get("type", "Thing")
            elabel   = ent.get("label", eid_str)
            eprops   = ent.get("properties", {})

            if not eid_str:
                continue

            eid_uri = _safe_uri(eid_str)
            
            # Declare Class if new
            cls_uri = ONTO[etype] if etype != "Thing" else OWL.Thing
            if etype not in declared_classes and etype != "Thing":
                g.add((cls_uri, RDF.type, OWL.Class))
                g.add((cls_uri, RDFS.label, Literal(etype)))
                declared_classes.add(etype)

            # Type assertion
            g.add((eid_uri, RDF.type, OWL.NamedIndividual))
            g.add((eid_uri, RDF.type, cls_uri))
            g.add((eid_uri, RDFS.label, Literal(elabel)))

            # Entity properties as datatype assertions
            for pk, pv in eprops.items():
                if pv is None or str(pv).strip() == "":
                    continue
                
                dp_uri = ONTO[pk]
                if pk not in declared_props:
                    g.add((dp_uri, RDF.type, OWL.DatatypeProperty))
                    g.add((dp_uri, RDFS.label, Literal(pk)))
                    declared_props.add(pk)
                
                # Try to guess datatype (very basic)
                val_str = str(pv)
                if re.match(r"^\d{4}$", val_str): # Likely year
                    g.add((eid_uri, dp_uri, Literal(val_str, datatype=XSD.gYear)))
                elif re.match(r"^\d+$", val_str):
                    g.add((eid_uri, dp_uri, Literal(val_str, datatype=XSD.integer)))
                else:
                    g.add((eid_uri, dp_uri, Literal(val_str)))

            total_entities += 1

        # ── 3. Add relationships as triples ───────────────
        for rel in rels:
            if not isinstance(rel, dict):
                continue

            subj_id   = rel.get("subject_id", "")
            pred_name = rel.get("predicate", "")
            obj_id    = rel.get("object_id", "")
            obj_type  = rel.get("object_type", "literal")
            datatype  = rel.get("datatype", "xsd:string")

            if not (subj_id and pred_name and obj_id):
                skipped_rels += 1
                continue

            subj_uri = _safe_uri(subj_id)
            pred_uri = ONTO[pred_name]

            if obj_type == "entity":
                obj_uri = _safe_uri(str(obj_id))
                g.add((subj_uri, pred_uri, obj_uri))

                if pred_name not in declared_props:
                    g.add((pred_uri, RDF.type, OWL.ObjectProperty))
                    g.add((pred_uri, RDFS.label, Literal(pred_name)))
                    declared_props.add(pred_name)
            else:
                dt_uri = _xsd_range(datatype)
                g.add((subj_uri, pred_uri,
                       Literal(str(obj_id), datatype=dt_uri)))
                
                if pred_name not in declared_props:
                    g.add((pred_uri, RDF.type, OWL.DatatypeProperty))
                    g.add((pred_uri, RDFS.label, Literal(pred_name)))
                    declared_props.add(pred_name)

            total_rels += 1

        # ── 4. Apply LLM-suggested OWL annotations ────────
        for pred_name, dom_class in annots.get("domain_hints", {}).items():
            g.add((ONTO[pred_name], RDFS.domain, ONTO[dom_class]))

        for pred_name, rng_val in annots.get("range_hints", {}).items():
            if rng_val.startswith("xsd:"):
                g.add((ONTO[pred_name], RDFS.range, _xsd_range(rng_val)))
            else:
                g.add((ONTO[pred_name], RDFS.range, ONTO[rng_val]))

        for pred_name, inv_name in annots.get("inverse_of", {}).items():
            g.add((ONTO[pred_name], OWL.inverseOf, ONTO[inv_name]))
            g.add((ONTO[inv_name], OWL.inverseOf, ONTO[pred_name]))

        for prop_name in annots.get("functional_properties", []):
            g.add((ONTO[prop_name], RDF.type, OWL.FunctionalProperty))

        for prop_name in annots.get("symmetric_properties", []):
            g.add((ONTO[prop_name], RDF.type, OWL.SymmetricProperty))



    print(f"\n  [triples] ✓ Graph built:")
    print(f"    Total triples : {len(g)}")
    print(f"    Entities      : {total_entities}")
    print(f"    Relationships : {total_rels}")
    print(f"    Classes       : {len(declared_classes)}")
    print(f"    Properties    : {len(declared_props)}")
    return g

