"""
triple_builder.py -- Convert enriched entities + relationships
into an rdflib Graph with proper OWL class hierarchy,
object properties (with domain/range), and datatype properties.
Produces a Protege-ready OWL ontology.
"""

import re
from rdflib import (Graph, Namespace, URIRef, Literal,
                    RDF, RDFS, OWL, XSD)
from rdflib.namespace import DC, FOAF, SKOS

# -- Namespaces --------------------------------------------
BASE_URI = "http://iiitb.ac.in/ontology/programmes#"
ONTO = Namespace(BASE_URI)
SCHEMA = Namespace("https://schema.org/")


def _safe_uri(id_str: str) -> URIRef:
    """Convert any string to a safe URI fragment."""
    # Handle already safe IDs or URLs
    if str(id_str).startswith("http"):
        return URIRef(id_str)
    
    safe = re.sub(r"[^a-zA-Z0-9_\-]", "_",
                  str(id_str).strip())
    safe = re.sub(r"_+", "_", safe).strip("_")
    return ONTO[safe or "unknown"]


def _xsd_range(type_str: str) -> URIRef:
    """Resolve xsd:type string to rdflib XSD URI."""
    if not type_str:
        return XSD.string
    t = type_str.replace("xsd:", "").strip()
    return XSD[t] if t else XSD.string


def _clean_rdfxml(xml_text: str) -> str:
    """
    Fixes duplicate rdf:ID in a single XML snippet by converting 
    subsequent occurrences to rdf:about="#ID".
    """
    ids_seen = set()
    
    def replacer(match):
        full_attr = match.group(0)
        id_val = match.group(1)
        if id_val in ids_seen:
            # Convert to about
            return f'rdf:about="#{id_val}"'
        ids_seen.add(id_val)
        return full_attr

    return re.sub(r'rdf:ID="([^"]+)"', replacer, xml_text)


def build_graph(enriched_list: list) -> Graph:
    """
    Build a fully autonomous OWL graph by merging RDF/XML snippets
    generated by the LLM. No hardcoded mapping logic.
    """
    master_graph = Graph()

    # Bind common namespaces for readability
    master_graph.bind("onto",   ONTO)
    master_graph.bind("owl",    OWL)
    master_graph.bind("rdfs",   RDFS)
    master_graph.bind("xsd",    XSD)
    master_graph.bind("dc",     DC)
    master_graph.bind("schema", SCHEMA)

    print(f"\n  [triples] Merging {len(enriched_list)} enriched chunks...")

    success_count = 0
    fail_count = 0

    for i, item in enumerate(enriched_list):
        if isinstance(item, str):
            try:
                # 1. Technical Fixes for Common LLM Syntax Errors
                
                # Fix duplicate rdf:ID in single snippet (converting to rdf:about)
                if "<rdf:RDF" in item:
                    item = _clean_rdfxml(item)
                
                # Parse the snippet into a temporary graph
                temp_g = Graph()
                
                # Parse with publicID = ontology base so that relative #-fragment
                # URIs (e.g. rdf:ID="teaches") resolve to onto:teaches instead of
                # staying as bare #teaches fragments. This ensures property
                # declarations and property usages share the same URI, which is
                # required for Protégé to display property assertions correctly.
                parse_kwargs = {"publicID": BASE_URI}

                # Try Turtle first (more robust for LLMs)
                try:
                    temp_g.parse(data=item, format="turtle", **parse_kwargs)
                except Exception as turtle_err:
                    # Fallback to XML
                    try:
                        temp_g.parse(data=item, format="xml", **parse_kwargs)
                    except Exception as xml_err:
                        print(f"    [triples] WARNING Chunk {i+1} parse failed:")
                        print(f"      - XML error:    {str(xml_err).strip()}")
                        fail_count += 1
                        continue
                
                # 2. Semantic Sanitization
                for s, p, o in temp_g:
                    # Skip triples whose subject/predicate are namespace declarations
                    if "xmlns" in str(s) or "xmlns" in str(p):
                        continue

                    # Skip triples with garbage subjects: XML comments, tag strings,
                    # and whitespace-embedded strings that the XML parser creates as
                    # side-effects of malformed LLM output (e.g. '!-- Classes --',
                    # 'rdf:RDF xmlns:...', 'owl:Class rdf:ID=.../').  
                    # After publicID resolution these show up as valid-looking http://
                    # URIs but contain spaces, newlines, bangs, or angle-brackets.
                    if isinstance(s, URIRef):
                        s_str = str(s)
                        if not s_str.startswith(("http://", "https://", "#")):
                            continue
                        # Reject URIs that contain XML artefact characters
                        if any(bad in s_str for bad in
                               [" ", "\n", "\t", "!--", "</", "rdf:RDF"]):
                            continue

                    if isinstance(o, URIRef):
                        o_str = str(o)
                        # If URI contains spaces or is exceptionally long without a
                        # protocol, it's likely a mis-categorised Literal
                        if " " in o_str or (len(o_str) > 250 and "://" not in o_str):
                            master_graph.add((s, p, Literal(o_str)))
                        else:
                            master_graph.add((s, p, o))
                    else:
                        master_graph.add((s, p, o))
                
                success_count += 1
            except Exception as e:
                print(f"    [triples] WARNING Chunk {i+1} unexpected error: {e}")
                fail_count += 1
        elif isinstance(item, dict):
            print(f"    [triples] WARNING Chunk {i+1} skipped (LLM error: {item.get('error', 'unknown')})")
            fail_count += 1

    # Ensure Ontology Header 
    onto_uri = URIRef(BASE_URI)
    if (onto_uri, RDF.type, OWL.Ontology) not in master_graph:
        master_graph.add((onto_uri, RDF.type, OWL.Ontology))
        master_graph.add((onto_uri, DC.title, 
                          Literal("Autonomous Institutional Knowledge Graph", lang="en")))
        master_graph.add((onto_uri, DC.description,
                          Literal("Emergent OWL ontology generated by autonomous pipeline.", lang="en")))
        master_graph.add((onto_uri, OWL.versionInfo, Literal("3.0-emergent")))

    print(f"  [triples] ✓ Merging complete:")
    print(f"    Total triples : {len(master_graph)}")
    print(f"    Chunks merged : {success_count}")
    print(f"    Chunks failed : {fail_count}")

    return master_graph

